# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

name: $(BuildDefinitionName)_$(Date:yyyyMMdd)

trigger:
- main

variables:
- name: ProjectToBuild
  value: src/android/Sudoku/

pool:
  vmImage: 'windows-latest'

steps:
- task: Gradle@2
  displayName: Build Project
  inputs:
    workingDirectory: $(ProjectToBuild)
    gradleWrapperFile: 'src/android/Sudoku/gradlew.bat'
    gradleOptions: '-Xmx3072m'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'assembleRelease'
    
- task: Gradle@2
  displayName: Run Tests
  inputs:
    workingDirectory: $(ProjectToBuild)
    gradleWrapperFile: 'src/android/Sudoku/gradlew.bat'
    gradleOptions: '-Xmx3072m'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'test'

- task: PublishTestResults@2
  displayName: Upload test results
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/TEST-*.xml'
    
- task: AndroidSigning@3
  displayName: Sign APKs
  inputs:
    apkFiles: '**/*.apk'
    apksign: true
    apksignerKeystoreFile: 'dgs_software_certificate.p12'
    apksignerKeystorePassword: '$(CodeSigningPassword)'
    apksignerKeystoreAlias: 'dgs_software'

- task: PowerShell@2
  displayName: Rename APKs
  inputs:
    targetType: 'inline'
    script: |
      Get-ChildItem "$($ProjectToBuild)" -Recurse | 
          Where {$_.Name -Match '-unsigned.apk'} | 
          Rename-Item -NewName {$_.name -replace '-unsigned','' } 

- task: PublishBuildArtifacts@1
  displayName: Publish Artifacts
  inputs:
    PathtoPublish: $(ProjectToBuild)/app/build/outputs
    ArtifactName: 'drop'
    publishLocation: 'Container'

